import { useState } from "react";
import { Link } from "react-router-dom";
import { Reveal } from "@/components/Reveal";
import { cn } from "@/lib/utils";

const SERVICES = [
  {
    n: "01",
    slug: "performance-marketing",
    title: "Performance Marketing",
    tagline: "Every rupee tracked. Every creative tested. Always on.",
    pitch: "Meta, Google & YouTube with a daily optimisation cadence — not a monthly report. Creative testing is built in from day one.",
    color: "#2563EB",
    bullets: [
      { label: "Meta Ads", sub: "Funnel architecture, creative testing, ROAS-first" },
      { label: "Google Ads", sub: "Search, Shopping, Display & YouTube" },
      { label: "SEO & AI Search", sub: "Organic rankings + LLM/AI Overview visibility + Perplexity & ChatGPT citation building" },
      { label: "WhatsApp Campaigns", sub: "Broadcast flows + retargeting sequences" },
      { label: "Weekly outcomes review", sub: "No monthly PDFs — real-time accountability" },
      { label: "Attribution & P&L", sub: "Know exactly what drives revenue" },
    ],
  },
  {
    n: "02",
    slug: "web-tech",
    title: "Web, App & AI Tech",
    tagline: "Fast, measurable digital products + AI systems — owned by you.",
    pitch: "Websites, Shopify stores, apps, AI chatbots and WhatsApp flows. Scoped, built, and handed over. Plus AI workflow automation that removes the repetitive work from your operations.",
    color: "#7C3AED",
    bullets: [
      { label: "High-converting websites", sub: "React, Next.js, Webflow — performance-first" },
      { label: "Shopify & ecommerce", sub: "Custom builds, apps, headless" },
      { label: "iOS & Android apps", sub: "Native and cross-platform development" },
      { label: "AI Chatbots", sub: "WhatsApp, website, Instagram DM — GPT-powered" },
      { label: "WhatsApp Automation", sub: "Flows, broadcasts, lead routing, booking" },
      { label: "CRM & API integrations", sub: "Zoho, HubSpot, Shopify, n8n / Make automations" },
      { label: "AI Workflow Automation", sub: "n8n, Make, Zapier flows — lead routing, auto-reporting, CRM enrichment. Repetitive work, removed." },
      { label: "Analytics setup", sub: "GA4, Mixpanel, Hotjar — proper tracking" },
    ],
  },
  {
    n: "03",
    slug: "social-media",
    title: "Social Media Management",
    tagline: "Your voice, consistently — built for the algorithm.",
    pitch: "Brand-led posting, reels and community built around your voice, not a template. We run it like a media company.",
    color: "#A8336E",
    bullets: [
      { label: "Content calendar", sub: "Instagram, LinkedIn, YouTube — channel-specific" },
      { label: "Reels production engine", sub: "Scripted, shot, edited — in-house" },
      { label: "Community management", sub: "DMs, comments, and brand voice" },
      { label: "Influencer outreach", sub: "Collaboration briefs and negotiation" },
      { label: "AI Caption & Hook Writing", sub: "Scroll-stopping copy generated by AI, refined by humans. Every post, every platform." },
      { label: "Monthly brand reporting", sub: "Audience insights and benchmark tracking" },
    ],
  },
  {
    n: "04",
    slug: "content-creation",
    title: "Content Creation",
    tagline: "Studio-grade content built in-house. Not briefed out.",
    pitch: "From brand identity to long-form video — everything produced without a third-party agency in the loop.",
    color: "#0F766E",
    bullets: [
      { label: "Social creatives (static + animated)", sub: "Feed posts, stories, ads" },
      { label: "Reels & short-form video", sub: "Full production — script to export" },
      { label: "Blog & SEO content", sub: "Long-form that ranks and converts" },
      { label: "Ad copywriting", sub: "For Google, Meta, email, and WhatsApp" },
      { label: "Brand identity & guidelines", sub: "Logo, palette, typography, voice" },
      { label: "AI Content Repurposing", sub: "One long-form video or blog → 15 pieces of content, automated and scheduled." },
    ],
  },
  {
    n: "05",
    slug: "personal-branding",
    title: "Personal Branding & Talent",
    tagline: "Make the founder the brand. Build influence like a media company.",
    pitch: "For founders and creators who want a lasting personal brand. We handle positioning, content, PR and brand deals.",
    color: "#DC2626",
    bullets: [
      { label: "Founder positioning & narrative", sub: "What you stand for and how you say it" },
      { label: "Weekly content production", sub: "LinkedIn, Instagram, YouTube — all channels" },
      { label: "PR & media placements", sub: "Podcasts, press, speaking slots" },
      { label: "Brand deals & negotiations", sub: "Outreach, terms, and contract review" },
      { label: "Talent management", sub: "For eligible creators and executives" },
    ],
  },
  {
    n: "06",
    slug: "ai-automation",
    title: "AI Growth Automation",
    tagline: "Your business on autopilot. We build the systems, you reap the results.",
    pitch: "From lead capture to close — we automate the entire growth engine so your team focuses only on what humans do best.",
    color: "#F59E0B",
    bullets: [
      { label: "Lead capture automation", sub: "AI forms, chatbots and landing pages that capture, qualify and route leads 24/7." },
      { label: "CRM & pipeline automation", sub: "n8n / Make flows that update your CRM, score leads, and trigger follow-ups automatically." },
      { label: "Reporting & analytics", sub: "Auto-generated weekly reports, dashboards, and performance alerts — zero manual effort." },
      { label: "WhatsApp & email sequences", sub: "Drip campaigns and behaviour-triggered messages that nurture leads to conversion." },
      { label: "AI content scheduling", sub: "Plan, generate and publish content across platforms with AI-assisted workflows." },
      { label: "Custom AI integrations", sub: "Connect your tools — Shopify, HubSpot, Zoho, Notion — into one seamless growth engine." },
    ],
  },
];

export function ServiceRows() {
  const [active, setActive] = useState<number | null>(null);

  return (
    <section id="services" className="py-24 md:py-32 bg-white">
      <div className="container-wide">
        <Reveal variant="up">
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-10 md:mb-12">
            <div>
              <p className="pill mb-5">Six services. One system.</p>
              <h2 className="heading-section max-w-xl">
                Everything your brand needs.<br />
                <em className="italic">Nothing it doesn't.</em>
              </h2>
            </div>
            <p className="text-muted-foreground max-w-xs text-base font-sans leading-relaxed">
              Pick what you need. Mix what you don't. Pricing scales with scope, not surprise.
            </p>
          </div>
        </Reveal>

        <div className="divide-y divide-border">
          {SERVICES.map((s, i) => {
            const isOpen = active === i;
            return (
              <div
                key={s.n}
                className={cn("service-row relative", isOpen && "is-open")}
                onMouseEnter={() => setActive(i)}
                onMouseLeave={() => setActive(null)}
              >
                <div className="absolute left-0 top-0 bottom-0 w-[3px] accent-bar" />

                {/* Header row */}
                <div className="w-full text-left grid md:grid-cols-12 gap-4 py-7 md:py-8 px-4 md:px-6 items-center cursor-default">
                  <div className="md:col-span-1 hidden md:block">
                    <span className="text-sm font-mono text-muted-foreground">{s.n}</span>
                  </div>
                  <div className="md:col-span-4">
                    <h3 className="font-serif text-xl md:text-2xl font-normal leading-snug">{s.title}</h3>
                  </div>
                  <div className="md:col-span-5 text-muted-foreground text-sm md:text-base font-sans hidden md:block">{s.tagline}</div>
                  <div className="md:col-span-2 flex justify-end items-center gap-3 md:gap-4">
                    <Link
                      to={`/services/${s.slug}`}
                      className="hidden md:block text-xs font-ui uppercase tracking-widest text-muted-foreground hover:text-foreground transition-colors"
                      style={{ fontFamily: "'Syne',sans-serif", fontWeight: 700 }}
                    >
                      Details
                    </Link>
                    <span
                      className="w-8 h-8 rounded-full border border-border flex items-center justify-center text-muted-foreground transition-all duration-300 shrink-0"
                      style={{ transform: isOpen ? "rotate(45deg)" : "rotate(0)", borderColor: isOpen ? s.color : undefined, color: isOpen ? s.color : undefined }}
                    >
                      <svg width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                        <line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" />
                      </svg>
                    </span>
                  </div>
                </div>

                {/* Expanded panel */}
                <div
                  className="grid transition-[grid-template-rows] duration-400 ease-out"
                  style={{ gridTemplateRows: isOpen ? "1fr" : "0fr" }}
                >
                  <div className="overflow-hidden">
                    <div className="px-4 md:px-6 pb-10 md:pb-12 md:pl-[calc(8.33%+1.5rem)]">
                      <p className="text-muted-foreground text-base mb-6 font-sans max-w-2xl">{s.pitch}</p>
                      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
                        {s.bullets.map((b) => (
                          <div key={b.label} className="rounded-xl border border-border bg-background p-4 hover:border-foreground/20 transition-colors">
                            <div className="flex items-center gap-2 mb-1">
                              <span className="w-1.5 h-1.5 rounded-full shrink-0" style={{ background: s.color }} />
                              <span className="font-ui text-sm font-semibold" style={{ fontFamily: "'Syne',sans-serif" }}>{b.label}</span>
                            </div>
                            <p className="text-xs text-muted-foreground font-sans pl-3.5">{b.sub}</p>
                          </div>
                        ))}
                      </div>
                      <div className="mt-6 flex gap-3">
                        <Link
                          to={`/services/${s.slug}`}
                          className="btn-gradient rounded-full px-6 py-2.5 text-xs inline-flex items-center gap-1.5"
                        >
                          Explore {s.title} →
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
